import mongoose from 'mongoose'

// Represents a user's purchase
const Purchase = new mongoose.Schema({
    // Generated by MongoDB
  PurchaseID: mongoose.Schema.Types.ObjectId,
  Retailer: String,
  BoughtTime: Date,// timestamp
  Cost: Number,// cost of purchase
  PaymentMethod: String,
  Category: String,
});

// Represents a Person that can login with a username (self-created) and password
// purchases: a list of references to the purchases objects
const User = new mongoose.Schema({
   username: String,
  // password hash provided by authentication plugin
  purchases: [mongoose.Schema.Types.ObjectId]
});